name: pr

on:
  workflow_dispatch:
    inputs:
      traces-exporters:
        description: 'OTEL exporter(s) to use for traces. Comma-separated if more than one.'
      metrics-exporters:
        description: 'OTEL exporter(s) to use for metrics. Comma-separated if more than one.'
      logs-exporters:
        description: 'OTEL exporter(s) to use for logs. Comma-separated if more than one.'
      default-endpoint:
        description: 'Remote destination for all data types. This is superseded by more specific data type endpoint specifications below.'
        required: false
      traces-endpoint:
        description: 'Remote destination for traces. Does not apply to all exporters (e.g. console). Note port and protocol (grpc vs https)'
        required: false
      metrics-endpoint:
        description: 'Remote destination for metrics. Does not apply to all exporters (e.g. console). Note port and protocol (grpc vs https)'
        required: false
      logs-endpoint:
        description: 'Remote destination for logs. Does not apply to all exporters (e.g. console). Note port and protocol (grpc vs https)'
        required: false

env:
    collector-url: lcedt.fatcowshrine.com:443
    otel-service-name: rapids-build-test

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install OpenTelemetry instrumentation
        run: |
          pip install opentelemetry-distro[otlp] opentelemetry-exporter-prometheus
          curl -L -o otel-cli-amd64.deb https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_0.4.5_linux_amd64.deb
          dpkg -i otel-cli-amd64.deb
          git clone -b add-conda-build-instrumentation https://github.com/msarahan/opentelemetry-python-contrib
          pip install -e ./opentelemetry-python-contrib/instrumentation/opentelemetry-instrumentation-conda-build
          opentelemetry-bootstrap -a install
      - name: Download gha-tools with git clone
        run: |
            git clone https://github.com/msarahan/gha-tools.git -b main /tmp/gha-tools
            echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}"
      - name: Setup telemetry
        id: setup-telemetry
        uses: krzko/setup-telemetry@v0.5.4
        with:
          observability-backend-url: ${{ env.collector-url }}
      - name: Write certificate files
        run: |
          mkdir -p /tmp/certs
          cat << EOF > /tmp/certs/ca.crt
          ${{ secrets.OTEL_EXPORTER_OTLP_CERTIFICATE }}
          EOF
          cat << EOF > /tmp/certs/client.crt
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE }}
          EOF
          cat << EOF > /tmp/certs/client.key
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_KEY }}
          EOF
      - name: Run build
        env:
            TRACEPARENT: ${{ steps.setup-telemetry.outputs.traceparent }}
            # This must be set for telemetry to be enabled. See rapids-otel-wrap script in gha-tools repo.
            OTEL_EXPORTER_OTLP_ENDPOINT: "${{ github.event.inputs.default-endpoint || 'https://lcedt.fatcowshrine.com/otlp-http/' }}"
            OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "${{ github.event.inputs.traces-endpoint || github.event.inputs.default-endpoint || 'https://lcedt.fatcowshrine.com/otlp-http/v1/traces' }}"
            OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "${{ github.event.inputs.metrics-endpoint || github.event.inputs.default-endpoint || 'https://lcedt.fatcowshrine.com/otlp-http/v1/metrics' }}"
            OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "${{ github.event.inputs.logs-endpoint || github.event.inputs.default-endpoint || 'https://lcedt.fatcowshrine.com/otlp-http/v1/logs' }}"
            OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
            OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
            OTEL_EXPORTER_OTLP_CERTIFICATE: "/tmp/certs/ca.crt"
            OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE: "/tmp/certs/client.crt"
            OTEL_EXPORTER_OTLP_CLIENT_KEY: "/tmp/certs/client.key"
            # These default to "console", so only need to be set for other values
            RAPIDS_JOB_ID: "Software Engineer"
            RAPIDS_OTEL_TRACES_EXPORTER: "${{ github.event.inputs.traces-exporters || 'otlp,console' }}"
            RAPIDS_OTEL_METRICS_EXPORTER: "${{ github.event.inputs.metrics-exporters || 'otlp,console' }}"
            RAPIDS_OTEL_LOGS_EXPORTER: "${{ github.event.inputs.logs-exporters || 'otlp,console' }}"
            RAPIDS_OTEL_SERVICE_NAME: "${{ env.otel-service-name }}"


        run: |
            rapids-conda-retry build click-feedstock
      - name: Export job telemetry
        if: always()
        uses: krzko/export-job-telemetry@v0.3.0
        with:
          created-at: ${{ steps.setup-telemetry.outputs.created-at }}
          job-status: ${{ job.status }}
          job-name: ${{ steps.setup-telemetry.outputs.job-name }}
          otel-exporter-otlp-endpoint: ${{ env.collector-url }}
          # otel-resource-attributes: "foo.new_attribute=123,${{ env.otel-resource-attributes }}"
          otel-service-name: ${{ env.otel-service-name }}
          started-at: ${{ steps.setup-telemetry.outputs.started-at }}
          traceparent: ${{ steps.setup-telemetry.outputs.traceparent }}
          otel-exporter-otlp-headers: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
